name: Clear Cache

on:
  push:
    branches:
      - 'main'

jobs:
  cache-clear:
    name: Clear Cache
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Cache Clear
        run: |
          git diff --name-only ${{ github.event.before }}..${{ github.event.after }} src/ | xargs -I{} curl "https://purge.jsdelivr.net/gh/Essura/essura@main/{}"